#! /usr/bin/env bash
set -ex
root=$(pwd)
env
if [ $cicd = "true" ]; then
    npm install -g webpack
    npm install -g webpack-cli
    yes | npm run install-all
fi

cd vue_microfrontend
if [ $cicd = "true" ]; then
    yes | npm install
fi
webpack --config ./webpack.config.js -p

cd ..
cp vue_microfrontend/build/microfrontend/microfrontend.js ./ui/microfrontend.js
cp index.html ./ui/index.html

cd $root