#! /usr/bin/env bash
set -ex
root=$(pwd)

if [ $stage = "acceptance" ]; then
    npm install -g webpack
    npm install -g webpack-cli
fi

cd vue_microfrontend
if [ $stage = "acceptance" ]; then
    yes | npm install
fi
webpack --config ./webpack.config.js -p


cd ..
cp vue_microfrontend/build/microfrontend/microfrontend.js ./ui/microfrontend.js
cp index.html ./ui/index.html

cd $root

# yq m api.yaml _template.yaml > template.yaml