AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
   
Globals:
    Function:
        Timeout: 15


Parameters:
        ServiceApiSubDomainName:
            Type: String
            Default: 'api'

        RootUrl:
            Type: String
            Default: '{{resolve:ssm:/account/root-url:1}}'

        SslCert: 
            Type: String
            Default: '{{resolve:ssm:/account/ssl-cert:1}}'
        
        RootSslCert: 
            Type: String
            Default: '{{resolve:ssm:/account/root-ssl-cert:1}}'
        
        HostedZoneId: 
            Type: String
            Default: '{{resolve:ssm:/account/hosted-zone-id:1}}'
        
        SkillName:
            Type: String
            Default: 'SellerDigital'

        BucketName:
            Type: String
            Default: ''
        
        Environment:
            Type: String
            Default: 'acceptance'

Conditions: 
      Acceptance: !Equals [ !Ref Environment, 'acceptance' ]

Resources: 
    
    APIDomainName:
        Type: 'AWS::ApiGatewayV2::DomainName'
        Properties:
            DomainName: !Join [ '', [ !Ref ServiceApiSubDomainName, '.', !Ref RootUrl ] ]
            DomainNameConfigurations:
                - EndpointType: REGIONAL
                  CertificateArn: !Ref SslCert
    
    WWWAPIDomainName:
        Type: AWS::ApiGateway::DomainName
        Properties:
          SecurityPolicy: TLS_1_2
          CertificateArn: !Ref SslCert
          DomainName: !Join [ '', [ 'www.', !Ref RootUrl ] ]
    
    RootAPIDomainName:
        Type: AWS::ApiGateway::DomainName
        Properties:
          SecurityPolicy: TLS_1_2
          CertificateArn: !Ref RootSslCert
          DomainName: !Join [ '', [  !Ref RootUrl ] ]


    ServiceApi:
        Type: AWS::Serverless::Api
        Properties:
            Name: ServiceApi
            StageName: 'Prod'
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'*'"
                AllowOrigin: "'*'"

    ServiceHttpApi:
        Type: AWS::Serverless::HttpApi


    APIBasePathMapping:
        Type: AWS::ApiGatewayV2::ApiMapping
        DependsOn: APIDomainName
        Properties:
            Stage: !Ref ServiceHttpApi.Stage
            DomainName: !Ref APIDomainName
            ApiId: !Ref ServiceHttpApi
    
    WWWBasePathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        DependsOn: WWWAPIDomainName
        Properties:
            Stage: !Ref ServiceApi.Stage
            DomainName: !Ref WWWAPIDomainName
            RestApiId: !Ref ServiceApi

    RootAPIBasePathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        DependsOn: RootAPIDomainName
        Properties:
            Stage: !Ref ServiceApi.Stage
            DomainName: !Ref RootAPIDomainName
            RestApiId: !Ref ServiceApi

    APIDomain:
        Type: 'AWS::Route53::RecordSetGroup'
        Properties:
            HostedZoneName:
                Fn::Join: [ '', [ Ref: RootUrl, '.' ] ]
            RecordSets:
            - Name: 
                Ref: APIDomainName
              Type: A
              AliasTarget:
                DNSName:
                    Fn::GetAtt: [APIDomainName, RegionalDomainName]
                HostedZoneId:
                    Fn::GetAtt: [APIDomainName, RegionalHostedZoneId]

    RootAPIDomain:
        DependsOn: RootAPIDomainName
        Type: 'AWS::Route53::RecordSetGroup'
        Properties:
            HostedZoneName:
                Fn::Join: [ '', [ Ref: RootUrl, '.' ] ]
            RecordSets:
            - Name: 
                Ref: RootUrl
              Type: A
              AliasTarget:
                DNSName:
                    Fn::GetAtt: [RootAPIDomainName, DistributionDomainName]
                HostedZoneId:
                    Fn::GetAtt: [RootAPIDomainName, DistributionHostedZoneId]

    WWWAPIDomain:
        Type: 'AWS::Route53::RecordSetGroup'
        Properties:
            HostedZoneName:
                Fn::Join: [ '', [ Ref: RootUrl, '.' ] ]
            RecordSets:
            - Name: 
                Ref: WWWAPIDomainName
              Type: A
              AliasTarget:
                DNSName:
                    Fn::GetAtt: [WWWAPIDomainName, DistributionDomainName]
                HostedZoneId:
                    Fn::GetAtt: [WWWAPIDomainName, DistributionHostedZoneId]
    
    
    RootStaticAssetsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref RootUrl
            WebsiteConfiguration:
                RedirectAllRequestsTo:
                    HostName: !Ref RootUrl
                    Protocol: https
    
    WWWStaticAssetsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: 
                Fn::Join: [ '', ['www.',Ref: RootUrl] ]
            WebsiteConfiguration:
                RedirectAllRequestsTo:
                    HostName: 
                        Fn::Join: [ '', ['www.',Ref: RootUrl] ]
    
    UiLambdaFunction:
            Type: AWS::Serverless::Function
            Properties:
                MemorySize: 3008
                Description: Serves microfrontend and shell html container
                CodeUri: ui/
                Handler: ui.lambda_handler
                Runtime: nodejs12.x
                Environment:
                    Variables:
                        RootUrl: !Ref RootUrl
                        ServiceApiSubDomainName: !Ref ServiceApiSubDomainName
                Events:
                    Get:
                        Type: Api
                        Properties:
                            Path: /
                            RestApiId: !Ref ServiceApi
                            Method: GET
                            
    ServiceApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            MemorySize: 3008
            CodeUri: service/
            Handler: service.lambda_handler
            Runtime: nodejs12.x
            Environment:
                Variables:
                    RootUrl: !Ref RootUrl
            # Policies:
            # - Statement:
            #     [{
            #       "Effect": "Allow",
            #       "Action": ["es:*","lambda:*","apigateway:*","s3:*","dynamodb:*"],
            #       "Resource": "*"
            #     }]
            Events:
                ApiPost:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ServiceHttpApi
                        Path: /
                        Method: post
                        # Auth:
                            #     Authorizer: CognitoAuthorizer
                # ApiPosts:
                #     Type: Api
                #     Properties:
                #         RestApiId: !Ref ServiceApi
                #         Path: /{resource}/{method}
                #         Method: post
                #         # Auth:
                #             #     Authorizer: CognitoAuthorizer
                # ApiOptions:
                #     Type: Api
                #     Properties:
                #         RestApiId: !Ref ServiceApi
                #         Path: /{resource}/{method}
                #         Method: options
                #         # Auth:
                #             #     Authorizer: CognitoAuthorizer

                        
Outputs:
    APIDomainName:
        Description: "Api Domain Name"
        Value: !Ref APIDomainName
    
    RootAPIDomainName:
        Description: "Root Api Domain Name"
        Value: !Ref RootAPIDomainName
    
    ApiUrl:
        Description: The API URL
        Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/"